// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using virtualmuseum.web.api.Services.DbContext;

#nullable disable

namespace virtualmuseum.web.api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241003150947_ChangedMediaFileIdToStringCompletely")]
    partial class ChangedMediaFileIdToStringCompletely
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("virtualmuseum.web.api.Services.Admin.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("virtualmuseum.web.data.Model.Inventory.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("InventoryType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("PositionX")
                        .HasColumnType("REAL");

                    b.Property<double>("PositionY")
                        .HasColumnType("REAL");

                    b.Property<double>("PositionZ")
                        .HasColumnType("REAL");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<double>("RotationX")
                        .HasColumnType("REAL");

                    b.Property<double>("RotationY")
                        .HasColumnType("REAL");

                    b.Property<double>("RotationZ")
                        .HasColumnType("REAL");

                    b.Property<double>("ScaleX")
                        .HasColumnType("REAL");

                    b.Property<double>("ScaleY")
                        .HasColumnType("REAL");

                    b.Property<double>("ScaleZ")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("virtualmuseum.web.data.Model.Inventory.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("virtualmuseum.web.data.Model.Inventory.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("virtualmuseum.web.data.Model.Inventory.TopographicalTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TopographicalTables");
                });

            modelBuilder.Entity("virtualmuseum.web.data.Model.Inventory.TopographicalTableTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MediaFileImage2DId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TopographicalTableId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TopographicalTableTopics");
                });

            modelBuilder.Entity("virtualmuseum.web.data.Model.Inventory.TopographicalTableTopicTimeSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TimeSeriesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TopographicalTableTopicId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TopographicalTableTopicTimeSeries");
                });

            modelBuilder.Entity("virtualmuseum.web.data.Model.Media.MediaFile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<float>("DurationInSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("virtualmuseum.web.data.Model.Media.MultimediaPresentation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MultimediaPresentations");
                });

            modelBuilder.Entity("virtualmuseum.web.data.Model.Media.PresentationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationInSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("MediaFileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MultimediaPresentationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PresentationItems");
                });

            modelBuilder.Entity("virtualmuseum.web.data.Model.TimeSeries.GeoEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GeoEventGroupId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("MultiMediaPresentationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GeoEvents");
                });

            modelBuilder.Entity("virtualmuseum.web.data.Model.TimeSeries.GeoEventGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TimeSeriesId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GeoEventGroups");
                });

            modelBuilder.Entity("virtualmuseum.web.data.Model.TimeSeries.TimeSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TimeSeries");
                });
#pragma warning restore 612, 618
        }
    }
}
